### ISSUE TITLE
Не выполняется поиск оазисов

### ISSUE THREAD

**Issue by PapIK1122** [Tegos/travian-elephant-finder#10]
Привет, подскажи пожалуйста, в чем может быть проблема? Не находит оазисы. Проблема в конфиге или в самом скрипте? Я вижу что пресет кукиес отличается от того что на стрине, мб в этом проблема?
Вот видео: https://youtu.be/uMMtLa8lgeY

**Comment by Tegos** [comment]
Привет. Ну здесь похоже просто травиан обновился. Обновил скрипт и описание. Смотрите, пробуйте.

**Comment by PapIK1122** [comment]
Попробовал снова:
https://youtu.be/cJD9OEalbY8
Не полечилось(

**Comment by Tegos** [comment]
Укажите свой сервер в конфиге, **travianServer**

**Comment by PapIK1122** [comment]
Да, не заметил.
Изменил на правильный, но это к сожалению не помогло, то же самое.

**Comment by PapIK1122** [comment]
Исправлено.
