### ISSUE TITLE
bad credentials due to token expiration

### ISSUE THREAD

**Issue by ThibautChaz** [Tegos/travian-elephant-finder#11]
for a long scan, there is an error "bad credentials" due to the expiration of the token I suppose? is there maybe something else that i miss ? any solutions ?

**Comment by ThibautChaz** [comment]
You had provided bad credentials
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! travian-elephant@0.0.1 collect: `node collectOasysPosition.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the travian-elephant@0.0.1 collect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thibaut\AppData\Roaming\npm-cache\_logs\2021-01-11T17_12_44_724Z-debug.log

**Comment by ThibautChaz** [comment]
My config.js :

const config = {
  cookie: 'JWT=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2MTAzODUxNTcsInByb3BlcnRpZXMiOnsic2FsdCI6ImEwMmRkOGQzZDNkMGU0N2U1NjlkYjg4YTdmOTVlYzgxIiwiaGFzaCI6IjgzNzA1OTgwODM3MDgzNzBmZDIzMGZkMGMxZDg2MWJmIiwibG9naW5JZCI6MTEzNjE2LCJsb3dSZXMiOmZhbHNlLCJtb2JpbGVPcHRpbWl6YXRpb25zIjpmYWxzZSwidmlsbGFnZVBlcnNwZWN0aXZlIjoicGVyc3BlY3RpdmVSZXNvdXJjZXMiLCJ1dWlkIjoiMDFiNjc4MDAtNDA1Ny0xMWViLTBkMTItMDEwMDAwMDAwNzM4IiwicHciOiI1ZjYwNGM1YzZiZDFmYjIxNzRiNWE2NzQ4MTVkYTk3NmQ0MDE3ODIxIn19.wwoEzRR-BjpSYZVPbfkxC_9Prq1phqXhr2eY8crLBkJ9neMrFwBenV_mpgjuRRvKWltVtjNymKBy6OJEQ5kpdaGUBhuHZigOCTWX3mPvOWq42pwiftShcuCbejVqqsjU9JSE5LaepGuF0tSZ6uLFlqU7RfcY36luz0TLJ3i47H2heNF0t3aL3zosiwFtNMXM1q1Eljgv8bmQsZdoZ5hSpxNEqK5uopZzphR1Dalk-tuxAdi9Lim5ENX2MFZ-5UtONTAi3BDSGAo73Tdw_RCVkYHdU8eeQ1mMXJzhl9wUxO9v8qLCLAvXVDXMcoKXl7u-_qgWfJcMJq5B6d-JvXr5lA; active_rallypoint_sub_filters_1=1; travian-language=fr-FR; mapId1=%7B%22grid%22%3Atrue%7D',
  travianServer: 'https://***.travian.fr',
  authorization: 'Bearer ************************',
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0',
  minX: -200,
  minY: 200,
  maxX: -112,
  maxY: 85,
  startX: -152,
  startY: 117,
  delayMin: 100,
  delayMax: 1500,
  jsonFileOasis: 'data/oasis.json',
  jsonFileOasisOccupied: 'data/oasis-occupied.json',
};

module.exports = config;

**Comment by Tegos** [comment]
Hello. Yes, seems you provided bad config for token. You should check readme and set up correct auth token and cookies.

**Comment by ThibautChaz** [comment]
if I do a test on a square of 9 boxes, it takes me 10 seconds and does not pose any problems

**Comment by ThibautChaz** [comment]
so i think the values ​​are good

For a scan of several hours, this error appeared because the token must have expired, right?

**Comment by Tegos** [comment]
Yes, you are right. The token needs renewing. I will try to research this problem, but seems it's not possible without login/pass.

**Comment by ThibautChaz** [comment]
We can cheat by refreshing automatically to keep the current session maybe? or it does not work?

**Comment by Tegos** [comment]
I don't know exactly, didn't play a long time). I will try to find some time for creating account in game and make some investigation.

**Comment by ThibautChaz** [comment]
Okey, i will follow your new suggestion !

**Comment by Tegos** [comment]
hello, there was a new release of tool, please check if the issue fixed.

**Comment by Tegos** [comment]
Hello. Did you try? Is there any updates? @ThibautChaz
