### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by MisticniCofi** [Tegos/travian-elephant-finder#2]
Can you please put some instructions on how to open it?

**Comment by Tegos** [comment]
Hello. See #1

**Comment by Tegos** [comment]
Hello. Sorry for long answer.  Check updated readme file.

**Comment by MisticniCofi** [comment]
Thanks bro, I'll check it out later.

Filip

Le mer. 27 févr. 2019 à 09:25, Ivan Mykhavko <notifications@github.com> a
écrit :
